# syntax = edrevo/dockerfile-plus
INCLUDE+ Dockerfile

# docker build -f Dockerfile.dev -t fabricmc-net . &&  docker run -p 7001:80 fabricmc-net 
WORKDIR /build
COPY . .

RUN ls

# Should match the github actions build
RUN bundler install --deployment && mkdir _site && bundler exec jekyll build && cd scripts && npm i && npm run build

FROM nginx:1.19
COPY --from=BUILD /build/_site /usr/share/nginx/html
