name: Deploy to Fabric Example Mod
on:
  push:
    paths:
      - scripts/**
      - cli/**
      - .github/workflows/deploy-template.yml

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.versions-lookup.outputs.result }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.10"
      - run: npm i
        working-directory: scripts
      - run: npm run buildLib
        working-directory: scripts
      - run: make build
        working-directory: cli
      - uses: actions/upload-artifact@v7
        with:
          name: cli
          path: cli/bundled.ts
      - uses: actions/github-script@v7
        id: versions-lookup
        with:
          script: |
            const { getGameVersions, getMajorMinecraftVersion, getMinorMinecraftVersion } = await import('${{ github.workspace }}/scripts/dist/fabric-template-generator.js');
            const stableVersions = (await getGameVersions()).filter(x => x.stable);
            const latestVersions = stableVersions.reduce((acc, x) => {
              const major = getMajorMinecraftVersion(x.version);
              const minor = getMinorMinecraftVersion(x.version);
              acc[`${major}.${minor}`] ??= x.version;
              return acc;
            }, {});
            return Object.entries(latestVersions).map(([branch, version]) => ({ branch, version }));
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      matrix:
        version: ${{ fromJSON(needs.build.outputs.versions) }}
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.10"
      - uses: actions/download-artifact@v8
        with:
          name: cli
      - uses: actions/checkout@v6
        id: existing-checkout
        with:
          repository: CelDaemon/fabric-example-mod
          ref: master
          path: repo
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: |
          if git ls-remote --exit-code --quiet origin '${{ matrix.version.branch }}'
          then
            git fetch origin '${{ matrix.version.branch }}'
            git switch '${{ matrix.version.branch }}'
          else
            git switch --orphan '${{ matrix.version.branch }}'
          fi
        working-directory: repo
      - run: mkdir gen
      - run: deno run -A ../bundled.ts init -n "Example Mod" -m modid -p "com.example" -v "${{ matrix.version.version }}" -o splitSources -o mojangMappings
        working-directory: gen
      - name: Set Github Actions as commit user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        working-directory: repo
      - name: Commit changes
        run: |
          git --work-tree ../gen add .
          git diff-index --quiet --cached HEAD || git commit -m 'Deployment from commit CelDaemon/fabricmc.net@${{ github.sha }}'
          git push -u origin '${{ matrix.version.branch }}'
        working-directory: repo

