name: Deploy to Fabric Example Mod
on:
  push:
    paths:
      - scripts/lib/**
      - cli/**
      - .github/workflows/deploy-template.yml

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.10"
      - run: npm i
        working-directory: scripts
      - run: npm run buildLib
        working-directory: scripts
      - run: make build
        working-directory: cli
      - uses: actions/upload-artifact@v7
        with:
          name: cli
          path: cli/bundled.ts
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      matrix:
        version:
          - branch: '1.14'
            version: '1.14.4'
          - branch: '1.15'
            version: '1.15.2'
          - branch: '1.16'
            version: '1.16.5'
          - branch: '1.17'
            version: '1.17.1'
          - branch: '1.18'
            version: '1.18.2'
          - branch: '1.19'
            version: '1.19.4'
          - branch: '1.20'
            version: '1.20.6'
          - branch: '1.21'
            version: '1.21.11'
          - branch: '26.1'
            version: '26.1.1'
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.10"
      - uses: actions/download-artifact@v8
        with:
          name: cli
      - uses: actions/checkout@v6
        id: existing-checkout
        with:
          repository: CelDaemon/fabric-example-mod
          ref: master
          path: repo
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: |
          if git ls-remote --exit-code --quiet origin '${{ matrix.version.branch }}'
          then
            git fetch origin '${{ matrix.version.branch }}'
            git switch '${{ matrix.version.branch }}'
          else
            git switch --orphan '${{ matrix.version.branch }}'
          fi
        working-directory: repo
      - run: mkdir gen
      - run: deno run -A ../bundled.ts init -n "Example Mod" -m modid -p "com.example" -v "${{ matrix.version.version }}" -o splitSources -o mojangMappings
        working-directory: gen
      - name: Set Github Actions as commit user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        working-directory: repo
      - name: Commit changes
        run: |
          git --work-tree ../gen add .
          git diff-index --quiet --cached HEAD || git commit -m 'Deployment from commit CelDaemon/fabricmc.net@${{ github.sha }}'
          git push -u origin '${{ matrix.version.branch }}'
        working-directory: repo

