name: Generator Test
on: 
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.34.0"
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - run: make run test
        working-directory: ./cli
      - uses: actions/upload-artifact@v4
        with:
          path: 
            cli/tests/1.*/**